"""OpenAI Responses API streaming converter."""

from __future__ import annotations

import json
import logging
import time
from enum import Enum
from typing import AsyncIterator, Optional

from app.models.common import ModelType
from app.utils.sse import format_sse_done, format_sse_event, generate_id
from app.utils.tool_call_ids import to_call

logger = logging.getLogger(__name__)


class StreamPhase(str, Enum):
    """State machine phases for streaming."""

    IDLE = "idle"
    REASONING = "reasoning"
    CONTENT = "content"
    TOOL_CALLS = "tool_calls"
    DONE = "done"


async def stream_openai_responses(
    deepseek_stream: AsyncIterator[dict],
    original_model: str,
    model_type: ModelType,
    response_id: str,
) -> AsyncIterator[str]:
    """Convert a DeepSeek SSE stream to OpenAI Responses API SSE format.

    The Responses API uses a different SSE event format with named events
    and a specific lifecycle:
    - response.created
    - response.in_progress
    - response.output_item.added
    - response.content_part.added
    - response.output_text.delta (or response.reasoning.delta)
    - response.output_text.done
    - response.content_part.done
    - response.output_item.done
    - response.completed

    For tool calls, emits:
    - response.output_item.added  (type: function_call)
    - response.function_call_arguments.delta
    - response.function_call_arguments.done
    - response.output_item.done   (type: function_call)

    Args:
        deepseek_stream: Async iterator of parsed SSE chunks from DeepSeek.
        original_model: The original model name requested by the client.
        model_type: Whether the model is a chat or reasoner.
        response_id: The response ID to use (generated by the router).

    Yields:
        Formatted SSE event strings.
    """
    is_reasoner = model_type == ModelType.REASONER
    reasoning_id = f"rs_{generate_id()}"
    message_id = f"msg_{generate_id()}"
    created_at = int(time.time())
    phase = StreamPhase.IDLE
    accumulated_reasoning = ""
    accumulated_content = ""

    # Track output items for correct indexing
    # Items are emitted in order: [reasoning?, message?, function_call*]
    output_items: list[dict] = []  # track emitted output items
    message_emitted = False  # whether the message output item has been emitted

    # Saved state from message that was closed by tool_calls handler.
    # Used by _build_output to reconstruct the final output for
    # response.completed when message was already closed during streaming.
    saved_message_id = ""
    saved_message_content = ""

    # Tool call tracking: index -> {id, name, arguments, call_id}
    pending_tool_calls: dict[int, dict] = {}

    def _next_output_index() -> int:
        """Get the next output item index."""
        return len(output_items)

    # Emit initial events
    yield format_sse_event({
        "type": "response.created",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "queued",
            "model": original_model,
            "output": [],
        },
    })

    yield format_sse_event({
        "type": "response.in_progress",
        "response": {
            "id": response_id,
            "object": "response",
            "created_at": created_at,
            "status": "in_progress",
            "model": original_model,
            "output": [],
        },
    })

    async for chunk in deepseek_stream:
        if not chunk.get("choices"):
            continue

        for choice in chunk["choices"]:
            delta = choice.get("delta", {})
            finish_reason = choice.get("finish_reason")

            # Handle reasoning_content
            reasoning_text = delta.get("reasoning_content")
            if reasoning_text is not None:
                if phase == StreamPhase.IDLE:
                    phase = StreamPhase.REASONING
                    # Emit reasoning output item added
                    out_idx = _next_output_index()
                    yield format_sse_event({
                        "type": "response.output_item.added",
                        "output_index": out_idx,
                        "item": {
                            "type": "reasoning",
                            "id": reasoning_id,
                            "summary": [],
                        },
                    })
                    output_items.append({"type": "reasoning", "id": reasoning_id})
                    yield format_sse_event({
                        "type": "response.content_part.added",
                        "part": {"type": "summary_text", "text": ""},
                        "output_index": out_idx,
                        "content_index": 0,
                    })

                accumulated_reasoning += reasoning_text
                # Find reasoning output index
                reasoning_out_idx = 0  # reasoning is always first if present
                yield format_sse_event({
                    "type": "response.reasoning.delta",
                    "output_index": reasoning_out_idx,
                    "content_index": 0,
                    "delta": reasoning_text,
                })

            # Handle tool_calls
            tool_calls = delta.get("tool_calls")
            if tool_calls:
                # Close any open content/reasoning before starting tool calls
                if phase == StreamPhase.REASONING:
                    reasoning_out_idx = 0
                    yield format_sse_event({
                        "type": "response.reasoning.done",
                        "output_index": reasoning_out_idx,
                        "content_index": 0,
                        "text": accumulated_reasoning,
                    })
                    yield format_sse_event({
                        "type": "response.content_part.done",
                        "part": {"type": "summary_text", "text": accumulated_reasoning},
                        "output_index": reasoning_out_idx,
                        "content_index": 0,
                    })
                    yield format_sse_event({
                        "type": "response.output_item.done",
                        "output_index": reasoning_out_idx,
                        "item": {
                            "type": "reasoning",
                            "id": reasoning_id,
                            "summary": [{"type": "summary_text", "text": accumulated_reasoning}],
                        },
                    })
                    accumulated_reasoning = ""  # Prevent re-close in finish handler

                if message_emitted and phase in (StreamPhase.CONTENT, StreamPhase.REASONING):
                    # Close the message output item before tool calls
                    msg_out_idx = _get_message_output_index(output_items)
                    yield format_sse_event({
                        "type": "response.output_text.done",
                        "output_index": msg_out_idx,
                        "content_index": 0,
                        "text": accumulated_content,
                    })
                    yield format_sse_event({
                        "type": "response.content_part.done",
                        "part": {"type": "output_text", "text": accumulated_content},
                        "output_index": msg_out_idx,
                        "content_index": 0,
                    })
                    yield format_sse_event({
                        "type": "response.output_item.done",
                        "output_index": msg_out_idx,
                        "item": {
                            "type": "message",
                            "id": message_id,
                            "role": "assistant",
                            "status": "completed",
                            "content": [{"type": "output_text", "text": accumulated_content, "annotations": []}],
                        },
                    })
                    # Save closed message info for final output reconstruction
                    saved_message_id = message_id
                    saved_message_content = accumulated_content
                    # Reset so subsequent content can start a new message
                    message_emitted = False
                    message_id = f"msg_{generate_id()}"
                    accumulated_content = ""

                if phase != StreamPhase.TOOL_CALLS:
                    phase = StreamPhase.TOOL_CALLS

                for tc_delta in tool_calls:
                    tc_index = tc_delta.get("index", 0)

                    # Initialize or update tool call data
                    if tc_index not in pending_tool_calls:
                        tc_id = to_call(tc_delta.get("id", ""))
                        call_id = tc_id  # Responses API uses call_id
                        pending_tool_calls[tc_index] = {
                            "id": tc_id,
                            "call_id": call_id,
                            "name": "",
                            "arguments": "",
                            "output_index": None,
                            "started": False,
                        }

                    tc = pending_tool_calls[tc_index]

                    # Update ID if present
                    if tc_delta.get("id"):
                        tc["id"] = to_call(tc_delta["id"])
                        tc["call_id"] = tc["id"]

                    # Update name if present
                    func_delta = tc_delta.get("function", {})
                    if func_delta.get("name"):
                        tc["name"] = func_delta["name"]

                    # Accumulate arguments
                    if func_delta.get("arguments"):
                        tc["arguments"] += func_delta["arguments"]

                    # Emit output_item.added on first chunk for this tool call
                    if not tc["started"]:
                        tc["started"] = True
                        out_idx = _next_output_index()
                        tc["output_index"] = out_idx
                        yield format_sse_event({
                            "type": "response.output_item.added",
                            "output_index": out_idx,
                            "item": {
                                "type": "function_call",
                                "id": tc["id"],
                                "call_id": tc["call_id"],
                                "name": tc["name"],
                                "arguments": "",
                            },
                        })
                        output_items.append({"type": "function_call", "id": tc["id"], "call_id": tc["call_id"], "name": tc["name"]})

                    # Emit function_call_arguments.delta
                    if func_delta.get("arguments"):
                        yield format_sse_event({
                            "type": "response.function_call_arguments.delta",
                            "output_index": tc["output_index"],
                            "delta": func_delta["arguments"],
                        })

            # Handle content
            content_text = delta.get("content")
            if content_text is not None:
                # Transition from reasoning to content
                if phase == StreamPhase.REASONING:
                    # Close reasoning
                    reasoning_out_idx = 0
                    yield format_sse_event({
                        "type": "response.reasoning.done",
                        "output_index": reasoning_out_idx,
                        "content_index": 0,
                        "text": accumulated_reasoning,
                    })
                    yield format_sse_event({
                        "type": "response.content_part.done",
                        "part": {"type": "summary_text", "text": accumulated_reasoning},
                        "output_index": reasoning_out_idx,
                        "content_index": 0,
                    })
                    yield format_sse_event({
                        "type": "response.output_item.done",
                        "output_index": reasoning_out_idx,
                        "item": {
                            "type": "reasoning",
                            "id": reasoning_id,
                            "summary": [{"type": "summary_text", "text": accumulated_reasoning}],
                        },
                    })
                    accumulated_reasoning = ""  # Prevent re-close in finish handler

                    phase = StreamPhase.CONTENT

                elif phase == StreamPhase.IDLE:
                    phase = StreamPhase.CONTENT

                elif phase == StreamPhase.TOOL_CALLS:
                    # Content arriving after tool calls — start a new message
                    # message_emitted was reset by the tool_calls handler
                    phase = StreamPhase.CONTENT
                    # A new message_id was already generated

                # Start message output item on first content chunk
                if not message_emitted:
                    message_emitted = True
                    msg_out_idx = _next_output_index()
                    yield format_sse_event({
                        "type": "response.output_item.added",
                        "output_index": msg_out_idx,
                        "item": {
                            "type": "message",
                            "id": message_id,
                            "role": "assistant",
                            "status": "in_progress",
                            "content": [],
                        },
                    })
                    output_items.append({"type": "message", "id": message_id})
                    yield format_sse_event({
                        "type": "response.content_part.added",
                        "part": {"type": "output_text", "text": ""},
                        "output_index": msg_out_idx,
                        "content_index": 0,
                    })

                accumulated_content += content_text
                msg_out_idx = _get_message_output_index(output_items)

                yield format_sse_event({
                    "type": "response.output_text.delta",
                    "output_index": msg_out_idx,
                    "content_index": 0,
                    "delta": content_text,
                })

            # Handle finish
            if finish_reason:
                # Close any open items based on current phase
                if phase == StreamPhase.REASONING:
                    # Close reasoning (no content came)
                    reasoning_out_idx = 0
                    yield format_sse_event({
                        "type": "response.reasoning.done",
                        "output_index": reasoning_out_idx,
                        "content_index": 0,
                        "text": accumulated_reasoning,
                    })
                    yield format_sse_event({
                        "type": "response.content_part.done",
                        "part": {"type": "summary_text", "text": accumulated_reasoning},
                        "output_index": reasoning_out_idx,
                        "content_index": 0,
                    })
                    yield format_sse_event({
                        "type": "response.output_item.done",
                        "output_index": reasoning_out_idx,
                        "item": {
                            "type": "reasoning",
                            "id": reasoning_id,
                            "summary": [{"type": "summary_text", "text": accumulated_reasoning}],
                        },
                    })

                # If reasoning was present but no message was ever opened,
                # emit an empty message to match convert_response() behavior
                if is_reasoner and accumulated_reasoning and not message_emitted:
                    msg_out_idx = _next_output_index()
                    yield format_sse_event({
                        "type": "response.output_item.added",
                        "output_index": msg_out_idx,
                        "item": {
                            "type": "message",
                            "id": message_id,
                            "role": "assistant",
                            "status": "in_progress",
                            "content": [],
                        },
                    })
                    output_items.append({"type": "message", "id": message_id})
                    yield format_sse_event({
                        "type": "response.content_part.added",
                        "part": {"type": "output_text", "text": ""},
                        "output_index": msg_out_idx,
                        "content_index": 0,
                    })
                    message_emitted = True

                # Close message output if it was opened
                if message_emitted and phase in (StreamPhase.CONTENT, StreamPhase.REASONING, StreamPhase.TOOL_CALLS):
                    msg_out_idx = _get_message_output_index(output_items)
                    yield format_sse_event({
                        "type": "response.output_text.done",
                        "output_index": msg_out_idx,
                        "content_index": 0,
                        "text": accumulated_content,
                    })
                    yield format_sse_event({
                        "type": "response.content_part.done",
                        "part": {"type": "output_text", "text": accumulated_content},
                        "output_index": msg_out_idx,
                        "content_index": 0,
                    })
                    yield format_sse_event({
                        "type": "response.output_item.done",
                        "output_index": msg_out_idx,
                        "item": {
                            "type": "message",
                            "id": message_id,
                            "role": "assistant",
                            "status": "completed",
                            "content": [{"type": "output_text", "text": accumulated_content, "annotations": []}],
                        },
                    })

                # Close any pending tool call items
                for tc_index, tc in sorted(pending_tool_calls.items()):
                    if tc["started"]:
                        # Emit function_call_arguments.done
                        yield format_sse_event({
                            "type": "response.function_call_arguments.done",
                            "output_index": tc["output_index"],
                            "arguments": tc["arguments"],
                        })
                        yield format_sse_event({
                            "type": "response.output_item.done",
                            "output_index": tc["output_index"],
                            "item": {
                                "type": "function_call",
                                "id": tc["id"],
                                "call_id": tc["call_id"],
                                "name": tc["name"],
                                "arguments": tc["arguments"],
                            },
                        })

                phase = StreamPhase.DONE

                # Get usage from the chunk if available
                usage_data = chunk.get("usage") or {}

                # Build final output list
                final_output = _build_output(
                    is_reasoner, accumulated_reasoning, reasoning_id,
                    accumulated_content, message_id,
                    pending_tool_calls,
                    saved_message_id, saved_message_content,
                    output_items,
                )

                # Determine status and incomplete_details from finish_reason
                stream_status = "completed"
                incomplete_details = None
                if finish_reason == "length":
                    stream_status = "incomplete"
                    incomplete_details = {"reason": "max_tokens"}
                elif finish_reason == "content_filter":
                    stream_status = "incomplete"
                    incomplete_details = {"reason": "content_filter"}

                # Emit completion
                yield format_sse_event({
                    "type": "response.completed",
                    "response": {
                        "id": response_id,
                        "object": "response",
                        "created_at": created_at,
                        "status": stream_status,
                        "model": original_model,
                        "output": final_output,
                        "incomplete_details": incomplete_details,
                        "usage": {
                            "input_tokens": usage_data.get("prompt_tokens", 0),
                            "output_tokens": usage_data.get("completion_tokens", 0),
                            "total_tokens": usage_data.get("total_tokens", 0),
                        },
                    },
                })

    # If stream ended without finish_reason — close any open items
    if phase != StreamPhase.DONE:
        # Close reasoning if open (reasoning started but never closed)
        if accumulated_reasoning:
            yield format_sse_event({
                "type": "response.reasoning.done",
                "output_index": 0,
                "content_index": 0,
                "text": accumulated_reasoning,
            })
            yield format_sse_event({
                "type": "response.content_part.done",
                "part": {"type": "summary_text", "text": accumulated_reasoning},
                "output_index": 0,
                "content_index": 0,
            })
            yield format_sse_event({
                "type": "response.output_item.done",
                "output_index": 0,
                "item": {
                    "type": "reasoning",
                    "id": reasoning_id,
                    "summary": [{"type": "summary_text", "text": accumulated_reasoning}],
                },
            })

        # Close message output if it was opened
        if message_emitted:
            msg_out_idx = _get_message_output_index(output_items)
            yield format_sse_event({
                "type": "response.output_text.done",
                "output_index": msg_out_idx,
                "content_index": 0,
                "text": accumulated_content,
            })
            yield format_sse_event({
                "type": "response.content_part.done",
                "part": {"type": "output_text", "text": accumulated_content},
                "output_index": msg_out_idx,
                "content_index": 0,
            })
            yield format_sse_event({
                "type": "response.output_item.done",
                "output_index": msg_out_idx,
                "item": {
                    "type": "message",
                    "id": message_id,
                    "role": "assistant",
                    "status": "incomplete",
                    "content": [{"type": "output_text", "text": accumulated_content, "annotations": []}],
                },
            })

        # Close any pending tool call items
        for tc_index, tc in sorted(pending_tool_calls.items()):
            if tc.get("started"):
                yield format_sse_event({
                    "type": "response.function_call_arguments.done",
                    "output_index": tc["output_index"],
                    "arguments": tc["arguments"],
                })
                yield format_sse_event({
                    "type": "response.output_item.done",
                    "output_index": tc["output_index"],
                    "item": {
                        "type": "function_call",
                        "id": tc["id"],
                        "call_id": tc["call_id"],
                        "name": tc["name"],
                        "arguments": tc["arguments"],
                    },
                })

        # Build complete output array including saved_message for accurate response
        final_output = _build_output(
            is_reasoner, accumulated_reasoning, reasoning_id,
            accumulated_content, message_id,
            pending_tool_calls,
            saved_message_id, saved_message_content,
            output_items,
        )

        yield format_sse_event({
            "type": "response.failed",
            "response": {
                "id": response_id,
                "status": "failed",
                "model": original_model,
                "output": final_output,
            },
        })

    yield format_sse_done()


def _get_message_output_index(output_items: list[dict]) -> int:
    """Find the output index of the most recent message item.

    Uses the LAST message item in output_items, not the first. This matters
    when tool_calls closed the first message and new content opened a second
    message — the stale (closed) message entry at a lower index must not be
    returned for the newer message's delta events.
    """
    last_idx = None
    for i, item in enumerate(output_items):
        if item.get("type") == "message":
            last_idx = i
    if last_idx is not None:
        return last_idx
    # Should not be reached — all callers guard with message_emitted
    logger.warning("No message item found, fallback index=0")
    return 0


def _build_output(
    is_reasoner: bool,
    reasoning: str,
    reasoning_id: str,
    content: str,
    message_id: str,
    pending_tool_calls: dict[int, dict],
    saved_message_id: str = "",
    saved_message_content: str = "",
    output_items: list | None = None,
) -> list:
    """Build the output array for the completed response.

    Uses output_items order to reconstruct the final output array in the
    correct sequence (matching streaming event order, not type grouping).

    Args:
        is_reasoner: Whether the model is a reasoner.
        reasoning: Accumulated reasoning text (or empty).
        reasoning_id: ID for the reasoning item.
        content: Current accumulated content. Empty if message was closed
            by tool_calls handler (content saved in saved_message_content).
        message_id: Current message ID. If message was closed by tool_calls
            handler, this is a regenerated ID for a potential new message.
        pending_tool_calls: Dict of tool calls being accumulated.
        saved_message_id: ID of message that was closed by tool_calls handler.
        saved_message_content: Content of message closed by tool_calls handler.
        output_items: Ordered list of emitted output item descriptors, used
            to determine the correct sequence of items in the output array.
    """
    if output_items:
        return _build_output_from_items(
            output_items, reasoning, reasoning_id,
            content, message_id, pending_tool_calls,
            saved_message_id, saved_message_content, is_reasoner,
        )

    # Fallback for callers without output_items
    output = []
    if is_reasoner and reasoning:
        output.append({
            "type": "reasoning",
            "id": reasoning_id,
            "summary": [{"type": "summary_text", "text": reasoning}],
        })

    if saved_message_content:
        output.append({
            "type": "message",
            "id": saved_message_id,
            "role": "assistant",
            "status": "completed",
            "content": [{"type": "output_text", "text": saved_message_content, "annotations": []}],
        })
    if content:
        output.append({
            "type": "message",
            "id": message_id,
            "role": "assistant",
            "status": "completed",
            "content": [{"type": "output_text", "text": content, "annotations": []}],
        })
    if not content and not saved_message_content and is_reasoner and reasoning:
        output.append({
            "type": "message",
            "id": message_id,
            "role": "assistant",
            "status": "completed",
            "content": [{"type": "output_text", "text": "", "annotations": []}],
        })
    for tc_index, tc in sorted(pending_tool_calls.items()):
        if tc.get("started"):
            output.append({
                "type": "function_call",
                "id": tc["id"],
                "call_id": tc["call_id"],
                "name": tc["name"],
                "arguments": tc["arguments"],
            })
    return output


def _build_output_from_items(
    output_items: list[dict],
    reasoning: str,
    reasoning_id: str,
    content: str,
    message_id: str,
    pending_tool_calls: dict[int, dict],
    saved_message_id: str,
    saved_message_content: str,
    is_reasoner: bool,
) -> list:
    """Build output array ordered by output_items emission sequence."""
    output = []

    # Build lookup: tool call index -> tool call data
    tc_by_item_id: dict[str, dict] = {}
    for tc_index, tc in sorted(pending_tool_calls.items()):
        if tc.get("started"):
            item_id = tc.get("id", "")
            if item_id:
                tc_by_item_id[item_id] = tc

    for item in output_items:
        item_type = item.get("type")

        if item_type == "reasoning" and is_reasoner and reasoning:
            output.append({
                "type": "reasoning",
                "id": reasoning_id,
                "summary": [{"type": "summary_text", "text": reasoning}],
            })

        elif item_type == "message":
            item_id = item.get("id", "")

            # Match against saved_message or current message
            if saved_message_content and item_id == saved_message_id:
                output.append({
                    "type": "message",
                    "id": saved_message_id,
                    "role": "assistant",
                    "status": "completed",
                    "content": [{"type": "output_text", "text": saved_message_content, "annotations": []}],
                })
            elif item_id == message_id and content:
                output.append({
                    "type": "message",
                    "id": message_id,
                    "role": "assistant",
                    "status": "completed",
                    "content": [{"type": "output_text", "text": content, "annotations": []}],
                })
            elif item_id == message_id and not content and is_reasoner and reasoning:
                # Reasoning-only: empty message
                output.append({
                    "type": "message",
                    "id": message_id,
                    "role": "assistant",
                    "status": "completed",
                    "content": [{"type": "output_text", "text": "", "annotations": []}],
                })

        elif item_type == "function_call":
            item_id = item.get("id", "")
            tc = tc_by_item_id.get(item_id)
            if tc:
                output.append({
                    "type": "function_call",
                    "id": tc["id"],
                    "call_id": tc["call_id"],
                    "name": tc["name"],
                    "arguments": tc["arguments"],
                })

    return output
